"use client";
import {useEffect,useId,useRef,useState} from "react";
import {searchPlaces} from "@/app/actions/locations";
import type {PlaceSuggestion} from "@/lib/entries/location";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Button} from "@/components/ui/button";
export function LocationField({defaultValue="",invalid=false,describedBy}:{defaultValue?:string|null;invalid?:boolean;describedBy?:string}){
 const id=useId(),[text,setText]=useState(defaultValue??""),[places,setPlaces]=useState<PlaceSuggestion[]>([]),[active,setActive]=useState(-1),[configured,setConfigured]=useState<boolean|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[search,setSearch]=useState(false);
 const sequence=useRef(0);
 useEffect(()=>{let live=true;void searchPlaces({operation:"status"}).then(r=>{if(live){setConfigured(r.configured??false);if(r.error)setMessage(r.error);}}).catch(()=>{if(live){setConfigured(false);setMessage("Could not connect to location search. You can still enter a place name.");}});return()=>{live=false;};},[]);
 useEffect(()=>{if(!search||!configured||text.trim().length<3)return;const current=++sequence.current;let live=true;const timer=setTimeout(async()=>{setBusy(true);try{const r=await searchPlaces({operation:"search",query:text});if(!live||current!==sequence.current)return;setPlaces(r.places??[]);setActive(-1);setMessage(r.error??(!r.places?.length?"No places found. Try a nearby street or another name.":""));}catch{if(live&&current===sequence.current)setMessage("Search was interrupted. Try typing again or enter a place name.");}finally{if(live&&current===sequence.current)setBusy(false);}},800);return()=>{live=false;clearTimeout(timer);};},[text,search,configured]);
 function choose(place:PlaceSuggestion){sequence.current++;setSearch(false);setPlaces([]);setText(place.label);setActive(-1);setBusy(false);setMessage("Place selected.");}
 function nearby(){if(!navigator.geolocation){setMessage("This browser cannot find your location.");return;}setSearch(false);sequence.current++;const current=sequence.current;setBusy(true);setMessage("Allow location access to find nearby places.");navigator.geolocation.getCurrentPosition(async position=>{try{const r=await searchPlaces({operation:"nearby",latitude:position.coords.latitude,longitude:position.coords.longitude});if(current!==sequence.current)return;setPlaces(r.places??[]);setActive(-1);setMessage(r.error??(r.places?.length?"Choose a nearby place below.":"No nearby places found. Search for a name instead."));}catch{if(current===sequence.current)setMessage("Nearby search was interrupted. Try again.");}finally{if(current===sequence.current)setBusy(false);}},()=>{if(current===sequence.current){setBusy(false);setMessage("Location access was unavailable. Search for a place instead.");}},{enableHighAccuracy:false,timeout:10000,maximumAge:60000});}
 return <div className="relative space-y-2"><Label htmlFor={id}>Location <span className="font-normal text-muted-foreground">optional</span></Label><Input id={id} name="location" role="combobox" aria-autocomplete="list" aria-expanded={places.length>0} aria-controls={id+"-results"} aria-activedescendant={active>=0?id+"-option-"+active:undefined} autoComplete="off" aria-invalid={invalid} aria-describedby={describedBy??id+"-help"} value={text} maxLength={240} placeholder={configured?"Search for a place":"Place name"} onChange={e=>{sequence.current++;setText(e.target.value);setSearch(true);setPlaces([]);setActive(-1);setMessage("");setBusy(false);}} onKeyDown={e=>{if(e.key==="Escape"){sequence.current++;setPlaces([]);setSearch(false);setBusy(false);}if((e.key==="ArrowDown"||e.key==="ArrowUp")&&places.length){e.preventDefault();setActive(i=>e.key==="ArrowDown"?Math.min(i+1,places.length-1):Math.max(i-1,0));}if(e.key==="Enter"&&active>=0&&places[active]){e.preventDefault();choose(places[active]);}}}/>
 {places.length?<ul id={id+"-results"} role="listbox" className="relative z-10 max-h-64 overflow-auto rounded-lg border bg-card shadow-lg">{places.map((p,i)=><li key={p.id} id={id+"-option-"+i} role="option" aria-selected={i===active} className={i===active?"bg-secondary":""}><button type="button" className="min-h-12 w-full px-4 py-3 text-left text-sm hover:bg-secondary" onClick={()=>choose(p)}>{p.label}</button></li>)}</ul>:null}
 {configured?<div className="flex flex-wrap items-center justify-between gap-2"><Button type="button" variant="ghost" size="sm" disabled={busy} onClick={nearby}>Use my location</Button><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center text-xs text-muted-foreground underline">© OpenStreetMap contributors</a></div>:null}
 <p id={id+"-help"} role="status" className="text-sm leading-6 text-muted-foreground">{busy?"Finding places…":message||(configured===false?"Location search is unavailable. You can enter a place name.":configured?"Type at least three letters. Location searches use OpenStreetMap via Photon.":"Checking location search…")}</p>
 </div>;
}
export function SavedLocation({value}:{value:string}){return <>{value}</>;}
