-- No messages or private data leave this transaction.
begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(13);
create temporary table fcm_recovery_results(result text);
grant select,insert on fcm_recovery_results to authenticated,anon,service_role;
insert into fcm_recovery_results select is(private.fcm_retry_seconds(0),60,'first retry waits one minute');
insert into fcm_recovery_results select is(private.fcm_retry_seconds(3),480,'retry backoff grows');
insert into fcm_recovery_results select is(private.fcm_retry_seconds(4),900,'retry delay is capped');
insert into fcm_recovery_results select is(private.fcm_retry_seconds(26),900,'observed attempt count never overflows');
insert into fcm_recovery_results select is(private.fcm_retry_seconds(2147483647),900,'even maximum integer attempts remain bounded');
insert into fcm_recovery_results select is(private.fcm_delivery_expired(now(),null),false,'fresh aggregated activity remains deliverable');
insert into fcm_recovery_results select is(private.fcm_delivery_expired(now()-interval '2 hours',null),true,'old activity expires without removing inbox history');
insert into fcm_recovery_results select is(private.fcm_delivery_expired(now(),now()),true,'read activity no longer alerts');
set local role authenticated;
insert into fcm_recovery_results select throws_ok($$select public.authorize_fcm_dispatch(repeat('x',40))$$,'42501',null,'recipient cannot verify internal secrets');
insert into fcm_recovery_results select throws_ok($$select private.dispatch_due_fcm(1)$$,'42501',null,'recipient cannot run the worker');
reset role;
set local role anon;
insert into fcm_recovery_results select throws_ok($$select public.authorize_fcm_dispatch(repeat('x',40))$$,'42501',null,'anonymous cannot verify internal secrets');
reset role;
set local role service_role;
insert into fcm_recovery_results select is(public.authorize_fcm_dispatch(repeat('fictional-wrong-secret-',3)),false,'internal caller still needs the correct secret');
insert into fcm_recovery_results select is(public.authorize_fcm_dispatch(null),false,'missing secret is rejected');
reset role;
select result from fcm_recovery_results;
select * from finish();
rollback;
