import { expect, test } from "@playwright/test";

test("bucket lists support steps, filters, conversion, completion and memory", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/sign-in");
  await page.getByRole("button", { name: "Enter paired preview" }).click();
  await expect(page).toHaveURL(/\/home$/);
  await page.goto("/bucket");
  await page.getByRole("button", { name: "Create your first list" }).click();
  await page.getByLabel("List name", { exact: true }).fill("Our little adventures");
  await page.getByRole("button", { name: "Create list" }).click();
  await expect(page.getByRole("option", { name: "Our little adventures" })).toHaveCount(1);
  await page.goto("/bucket/new");
  await page.getByLabel("What would you love to do?").fill("Watch the sunrise together");
  await page.getByRole("button", { name: "Add category", exact: true }).click();
  await page.getByLabel("Category", { exact: true }).fill("Outdoors");
  await page.getByRole("button", { name: "Choose existing", exact: true }).click();
  await page.getByRole("button", { name: "Add category", exact: true }).click();
  await expect(page.getByLabel("Category", { exact: true })).toHaveValue("Outdoors");
  await page.getByLabel("Why this one?", { exact: false }).fill("Take a flask of coffee and find a quiet spot by the water.");
  await page.getByLabel("Priority", { exact: true }).selectOption("dream");
  await page.route("**/bucket/new", (route) => route.request().method() === "POST" ? route.abort("internetdisconnected") : route.continue());
  await page.getByRole("button", { name: "Save this idea" }).click();
  await expect(page.getByRole("status")).toContainText("Connection interrupted");
  await expect(page.getByLabel("What would you love to do?")).toHaveValue("Watch the sunrise together");
  await page.unroute("**/bucket/new");
  await page.getByRole("button", { name: "Save this idea" }).click();
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  const ideaUrl = page.url();
  await page.getByText("Edit the idea", { exact: true }).click();
  await page.screenshot({ path: `test-results/bucket-editor-${testInfo.project.name}.png` });
  await page.getByLabel("Location", { exact: false }).fill("By the water");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByText("By the water", { exact: true })).toBeVisible();
  for (const label of ["Choose a viewpoint", "Pack coffee"]) { await page.getByLabel("Next little step").fill(label); await page.getByRole("button", { name: "Add step", exact: true }).click(); await expect(page.getByLabel("Next little step")).toHaveValue(""); }
  if (testInfo.project.name === "desktop-chromium") {
    await page.getByRole("button", { name: "Move Pack coffee up" }).focus();
    await page.keyboard.press("Enter");
    await expect(page.getByLabel("Step 1", { exact: true })).toHaveValue("Pack coffee");
  } else {
    await expect(page.getByLabel("Step 2", { exact: true })).toHaveValue("Pack coffee");
  }
  await page.getByRole("checkbox", { name: "Complete Pack coffee" }).click();
  await expect(page.getByRole("checkbox", { name: "Complete Pack coffee" })).toBeChecked();
  await expect(page.getByText("1 of 2 complete", { exact: true })).toBeVisible();
  await page.getByLabel("Step 2", { exact: true }).fill("Find a quiet viewpoint");
  await page.getByRole("button", { name: "Save step", exact: true }).nth(1).click();
  await expect(page.getByRole("checkbox", { name: "Complete Find a quiet viewpoint" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Add step", exact: true })).toBeEnabled();
  const viewport = page.viewportSize()!;
  for (const width of [320, 768]) {
    await page.setViewportSize({ width, height: 800 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
    const stepBox = await page.getByLabel("Step 2", { exact: true }).boundingBox();
    expect(stepBox!.width).toBeGreaterThan(100);
    if (width === 320) {
      await expect(page.getByRole("button", { name: "Move Find a quiet viewpoint up" })).toBeHidden();
      await expect(page.getByRole("button", { name: "Move Find a quiet viewpoint down" })).toBeHidden();
      const inputBox = await page.getByLabel("Step 2", { exact: true }).boundingBox();
      const removeBox = await page.getByRole("button", { name: "Remove step Find a quiet viewpoint" }).boundingBox();
      expect(Math.abs(inputBox!.y - removeBox!.y)).toBeLessThanOrEqual(8);
    }
  }
  await page.setViewportSize(viewport);
  await page.screenshot({ path: `test-results/bucket-detail-${testInfo.project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
  await page.getByRole("link", { name: "Plan this", exact: true }).click();
  await expect(page.getByLabel("What are you planning?")).toHaveValue("Watch the sunrise together");
  await page.getByLabel("Starts", { exact: true }).fill("2027-08-14T05:00");
  await page.getByRole("button", { name: "Save this plan", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  await page.goto(ideaUrl);
  await page.getByRole("button", { name: "Mark complete", exact: true }).click();
  await expect(page.getByRole("heading", { name: "One more dream lived." })).toBeVisible();
  await page.getByRole("link", { name: "Save this as a memory" }).click();
  await page.getByRole("button", { name: "Save the memory" }).click();
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  await page.goto("/bucket");
  await page.getByRole("button", { name: "Options", exact: true }).click();
  await page.getByLabel("Status", { exact: true }).selectOption("completed");
  await page.route("**/bucket", (route) => route.request().method() === "POST" ? route.abort("internetdisconnected") : route.continue());
  await page.getByRole("button", { name: "Apply filters" }).click();
  await expect(page.getByRole("status")).toContainText("Connection interrupted");
  await page.unroute("**/bucket");
  await page.getByRole("button", { name: "Apply filters" }).click();
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.screenshot({ path: `test-results/bucket-list-${testInfo.project.name}.png`, fullPage: true });
  await page.getByRole("button", { name: "Options", exact: true }).click();
  await page.getByLabel("Status", { exact: true }).selectOption("idea");
  await page.getByRole("button", { name: "Apply filters" }).click();
  await expect(page.getByText("Room for your next idea.")).toBeVisible();
  await page.goto(ideaUrl);
  await page.getByRole("button", { name: "Delete this idea", exact: true }).click();
  await page.getByLabel("Type DELETE to confirm").fill("DELETE");
  await page.getByRole("button", { name: "Delete idea permanently" }).click();
  await expect(page).toHaveURL(/\/bucket$/);
  await page.goto("/memories");
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  await expect(page.getByRole("link", { name: "From your bucket list" })).toHaveCount(0);
  await page.goto("/bucket");
  await page.getByRole("button", { name: "Options", exact: true }).click();
  await page.getByLabel("Browse a list").selectOption({ label: "Our little adventures" });
  await page.getByText("Manage this list", { exact: true }).click();
  await page.getByLabel("List name", { exact: true }).last().fill("Small adventures");
  await page.getByRole("button", { name: "Rename list", exact: true }).click();
  await expect(page.getByRole("option", { name: "Small adventures", exact: true })).toHaveCount(1);
  await page.getByRole("button", { name: "Manage this list", exact: true }).click();
  await page.getByLabel("Type DELETE to confirm").fill("DELETE");
  await page.getByRole("button", { name: "Delete empty list" }).click();
  await expect(page.getByRole("option", { name: "Small adventures", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Close dialog", exact: true }).click();
  await expect(page.getByRole("heading", { name: "What would you love to do together?" })).toBeVisible();
});

test("bucket options preserve drafts on failure and support keyboard, narrow screens and dark mode", async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/sign-in");
  await page.getByRole("button", { name: "Enter paired preview" }).click();
  await expect(page).toHaveURL(/\/home$/);
  await page.goto("/bucket");
  const options = page.getByRole("button", { name: "Options", exact: true });
  await options.click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toHaveCount(1);
  await page.getByLabel("Status", { exact: true }).selectOption("completed");
  await page.screenshot({ path: `test-results/bucket-options-${testInfo.project.name}.png` });
  await page.getByRole("button", { name: "New list", exact: true }).click();
  await expect(dialog).toHaveCount(1);
  await expect(page.getByLabel("List name", { exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Back to options", exact: true }).click();
  await expect(page.getByLabel("Status", { exact: true })).toHaveValue("completed");
  await page.getByRole("button", { name: "Close dialog", exact: true }).focus();
  await page.keyboard.press("Tab");
  expect(await dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true);
  await page.keyboard.press("Shift+Tab");
  expect(await dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true);
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(options).toBeFocused();
  await options.click();
  await expect(page.getByLabel("Status", { exact: true })).toHaveValue("");
  await page.getByLabel("Priority", { exact: true }).selectOption("dream");
  await page.route("**/bucket", (route) => route.request().method() === "POST" ? route.abort("internetdisconnected") : route.continue());
  await page.getByRole("button", { name: "Apply filters", exact: true }).click();
  await expect(dialog.getByRole("status")).toContainText("Connection interrupted");
  await expect(page.getByLabel("Priority", { exact: true })).toHaveValue("dream");
  await page.unroute("**/bucket");
  await page.getByRole("button", { name: "Apply filters", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await options.click();
  await expect(page.getByLabel("Priority", { exact: true })).toHaveValue("dream");
  await page.setViewportSize({ width: 320, height: 640 });
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  const filterGrid = page.getByLabel("Status", { exact: true }).locator("xpath=ancestor::div[contains(@class, 'grid')][1]");
  expect((await filterGrid.evaluate((element) => getComputedStyle(element).gridTemplateColumns)).trim().split(/\s+/)).toHaveLength(1);
  await page.evaluate(() => document.documentElement.classList.add("dark"));
  await expect(page.getByRole("button", { name: "Apply filters", exact: true })).toHaveCSS("background-color", "rgb(223, 135, 154)");
  await expect(page.getByRole("button", { name: "New list", exact: true })).toHaveCSS("color", "rgb(223, 135, 154)");
  await page.screenshot({ path: `test-results/bucket-options-narrow-dark-${testInfo.project.name}.png` });
  await page.getByRole("button", { name: "Close dialog", exact: true }).click();
  await expect(options).toBeFocused();
});
