import { expect, test } from "@playwright/test";

test("bucket lists support steps, filters, conversion, completion and memory", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/sign-in");
  await page.getByRole("button", { name: "Enter paired preview" }).click();
  await expect(page).toHaveURL(/\/home$/);
  await page.goto("/bucket");
  await page.getByText("New list", { exact: true }).click();
  await page.getByLabel("List name", { exact: true }).fill("Our little adventures");
  await page.getByRole("button", { name: "Create list" }).click();
  await expect(page.getByRole("option", { name: "Our little adventures" })).toHaveCount(1);
  await page.goto("/bucket/new");
  await page.getByLabel("What would you love to do?").fill("Watch the sunrise together");
  await page.getByLabel("Category", { exact: false }).fill("Outdoors");
  await page.getByLabel("Why this one?", { exact: false }).fill("Take a flask of coffee and find a quiet spot by the water.");
  await page.getByLabel("Priority", { exact: true }).selectOption("dream");
  await page.route("**/bucket/new", (route) => route.request().method() === "POST" ? route.abort("internetdisconnected") : route.continue());
  await page.getByRole("button", { name: "Save this idea" }).click();
  await expect(page.getByRole("status")).toContainText("Connection interrupted");
  await expect(page.getByLabel("What would you love to do?")).toHaveValue("Watch the sunrise together");
  await page.unroute("**/bucket/new");
  await page.getByRole("button", { name: "Save this idea" }).click();
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  const ideaUrl = page.url();
  await page.getByText("Edit the idea", { exact: true }).click();
  await page.getByLabel("Location", { exact: false }).fill("By the water");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByText("By the water", { exact: true })).toBeVisible();
  await page.getByText("Edit the idea", { exact: true }).click();
  for (const label of ["Choose a viewpoint", "Pack coffee"]) { await page.getByLabel("Next little step").fill(label); await page.getByRole("button", { name: "Add step", exact: true }).click(); await expect(page.getByLabel("Next little step")).toHaveValue(""); }
  await page.getByRole("button", { name: "Move Pack coffee up" }).focus();
  await page.keyboard.press("Enter");
  await expect(page.getByLabel("Step 1", { exact: true })).toHaveValue("Pack coffee");
  await page.getByRole("checkbox", { name: "Complete Pack coffee" }).click();
  await expect(page.getByRole("checkbox", { name: "Complete Pack coffee" })).toBeChecked();
  await expect(page.getByText("1 of 2 complete", { exact: true })).toBeVisible();
  await page.getByLabel("Step 2", { exact: true }).fill("Find a quiet viewpoint");
  await page.getByRole("button", { name: "Save step", exact: true }).nth(1).click();
  await expect(page.getByRole("checkbox", { name: "Complete Find a quiet viewpoint" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Add step", exact: true })).toBeEnabled();
  await page.screenshot({ path: `test-results/bucket-detail-${testInfo.project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
  await page.getByRole("link", { name: "Plan this", exact: true }).click();
  await expect(page.getByLabel("What are you planning?")).toHaveValue("Watch the sunrise together");
  await page.getByLabel("Starts", { exact: true }).fill("2027-08-14T05:00");
  await page.getByRole("button", { name: "Save this plan", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  await page.goto(ideaUrl);
  await page.getByRole("button", { name: "Mark complete", exact: true }).click();
  await expect(page.getByRole("heading", { name: "One more dream lived." })).toBeVisible();
  await page.getByRole("link", { name: "Save this as a memory" }).click();
  await page.getByRole("button", { name: "Save the memory" }).click();
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  await page.goto("/bucket");
  await page.getByLabel("Status", { exact: true }).selectOption("completed");
  await page.route("**/bucket", (route) => route.request().method() === "POST" ? route.abort("internetdisconnected") : route.continue());
  await page.getByRole("button", { name: "Apply filters" }).click();
  await expect(page.getByRole("status")).toContainText("Connection interrupted");
  await page.unroute("**/bucket");
  await page.getByRole("button", { name: "Apply filters" }).click();
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Apply filters" })).toBeEnabled();
  await page.screenshot({ path: `test-results/bucket-list-${testInfo.project.name}.png`, fullPage: true });
  await page.getByLabel("Status", { exact: true }).selectOption("idea");
  await page.getByRole("button", { name: "Apply filters" }).click();
  await expect(page.getByText("Room for your next idea.")).toBeVisible();
  await page.goto(ideaUrl);
  await page.getByText("Delete this idea", { exact: true }).click();
  await page.getByLabel("Type DELETE to confirm").fill("DELETE");
  await page.getByRole("button", { name: "Delete idea permanently" }).click();
  await expect(page).toHaveURL(/\/bucket$/);
  await page.goto("/memories");
  await expect(page.getByRole("heading", { name: "Watch the sunrise together" })).toBeVisible();
  await expect(page.getByRole("link", { name: "From your bucket list" })).toHaveCount(0);
  await page.goto("/bucket");
  await page.getByLabel("Browse a list").selectOption({ label: "Our little adventures" });
  await page.getByText("Manage this list", { exact: true }).click();
  await page.getByLabel("List name", { exact: true }).last().fill("Small adventures");
  await page.getByRole("button", { name: "Rename list", exact: true }).click();
  await expect(page.getByRole("option", { name: "Small adventures", exact: true })).toHaveCount(1);
  await page.getByLabel("Type DELETE to confirm").fill("DELETE");
  await page.getByRole("button", { name: "Delete empty list" }).click();
  await expect(page.getByRole("heading", { name: "What would you love to do together?" })).toBeVisible();
});
