import { test,expect } from "@playwright/test";
test("memories preserve stories through editing, tags, filters and deletion",async({page},testInfo)=>{
 await page.emulateMedia({reducedMotion:"reduce"});
 await page.goto("/sign-in");await page.getByRole("button",{name:"Enter paired preview"}).click();await expect(page).toHaveURL(/\/home$/);
 await page.goto("/memories/new");
 await page.getByLabel("What do you want to remember?").fill("The last light on the harbour, and nowhere else to be.");
 await page.getByRole("button",{name:"Save the memory"}).click();
 await expect(page.getByText("Name this memory.")).toBeVisible();
 await expect(page.getByLabel("What do you want to remember?")).toHaveValue("The last light on the harbour, and nowhere else to be.");
 await page.getByLabel("Memory title").fill("An evening at the harbour");
 await page.getByLabel("Date",{exact:true}).fill("2026-08-20");await page.getByLabel("Location").fill("The old harbour");
 await page.getByLabel("Keep as a favorite").check();
 await page.route("**/memories/new",route=>route.abort("failed"),{times:1});
 await page.getByRole("button",{name:"Save the memory"}).click();
 await expect(page.locator("main").getByRole("alert")).toContainText("Your draft is still here");
 await expect(page.getByLabel("Memory title")).toHaveValue("An evening at the harbour");
 await expect(page.getByLabel("What do you want to remember?")).toHaveValue("The last light on the harbour, and nowhere else to be.");
 await page.getByRole("button",{name:"Save the memory"}).click();
 await expect(page).toHaveURL(/\/memories\/[0-9a-f-]+$/);const detail=page.url();
 await page.getByRole("link",{name:"Edit memory"}).click();
 await page.getByLabel("Tags").fill("Travel, little moments, travel");await page.getByLabel("How it felt").selectOption("5");
 await page.getByRole("button",{name:"Save changes"}).click();await expect(page.getByText("travel · little moments",{exact:true})).toBeVisible();
 await page.screenshot({path:"test-results/memories-detail-"+testInfo.project.name+".png",fullPage:true});
 await page.getByRole("link",{name:"Back to memories"}).click();
 await page.getByLabel("Find a tag").fill("travel");await page.getByLabel("Favorites only").check();
 await page.route("**/memories",route=>route.abort("failed"),{times:1});
 await page.getByRole("button",{name:"Apply filters"}).click();await expect(page.locator("main").getByRole("alert")).toContainText("Check your connection");
 await expect(page.getByLabel("Find a tag")).toHaveValue("travel");
 await page.getByRole("button",{name:"Apply filters"}).click();
 await expect(page.getByRole("heading",{name:"An evening at the harbour"})).toBeVisible();
 await page.screenshot({path:"test-results/memories-gallery-"+testInfo.project.name+".png",fullPage:true});
 await page.getByLabel("Find a tag").fill("other");await page.getByRole("button",{name:"Apply filters"}).click();await expect(page.getByText("No memories match just yet.")).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
 await page.goto(detail);await page.keyboard.press("Tab");await expect(page.locator(":focus-visible")).toBeVisible();
 await page.getByText("Delete this memory",{exact:true}).click();await page.getByLabel("Type DELETE to confirm").fill("DELETE");await page.getByRole("button",{name:"Permanently delete memory"}).click();await expect(page).toHaveURL(/\/memories$/);
 await expect(page.getByRole("heading",{name:"An evening at the harbour"})).toHaveCount(0);
});