import {test,expect} from "@playwright/test";
import {readFileSync} from "node:fs";
test.use({trace:"off",video:"off"});
test("connected account uploads, views and removes private photos and videos",async({page},testInfo)=>{
 test.skip(process.env.PHASE6_HOSTED!=="true","Explicit disposable-account hosted gate");
 test.setTimeout(180000);
 const fixture=JSON.parse(readFileSync("supabase/.temp/phase6-fixture.json","utf8"));
 await page.emulateMedia({reducedMotion:"reduce"});
 await page.goto("/sign-in");await page.getByLabel("Email",{exact:true}).fill(fixture.users[0].email);await page.getByLabel("Password",{exact:true}).fill(fixture.users[0].password);await page.getByRole("button",{name:"Sign in",exact:true}).click();
 await expect(page).toHaveURL(/\/home$/);
 await page.goto("/memories/"+fixture.memory);
 await page.getByLabel("Choose photos or videos").setInputFiles("tests/fixtures/phase6-fixture.png");
 await page.getByLabel("Caption for file 1").fill("Fictional test swatch");
 await page.getByRole("button",{name:"Upload selected files",exact:true}).click();
 await expect(page.getByRole("button",{name:/Open photo/})).toBeVisible({timeout:90000});
 await page.getByRole("button",{name:/Open photo/}).click();
 await expect(page.getByRole("dialog")).toBeVisible();
 await expect.poll(()=>page.getByRole("dialog").locator("img").evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);
 const download=page.getByRole("link",{name:"Download file"}),href=await download.getAttribute("href");
 const res=await page.request.get(href!,{maxRedirects:0});
 expect(res.status()).toBe(307);expect(res.headers()["cache-control"]).toContain("no-store");expect(res.headers().location).toContain("token=");
 await page.screenshot({path:".impeccable/qa/phase6-viewer-"+testInfo.project.name+".png",fullPage:false});
 await page.keyboard.press("Escape");await expect(page.getByRole("dialog")).not.toBeVisible();
 await page.getByLabel("Choose photos or videos").setInputFiles("tests/fixtures/phase6-video.mp4");
 await page.getByLabel("Caption for file 1").fill("CC0 video fixture");
 await page.getByRole("button",{name:"Upload selected files",exact:true}).click();
 await expect(page.getByText("1 photos · 1 videos",{exact:true})).toBeVisible({timeout:90000});await page.getByRole("link",{name:/Show more/}).click();await expect(page.getByRole("button",{name:/Open video/})).toBeVisible();
 expect(await page.locator("video").count()).toBe(0);
 await page.getByRole("button",{name:/Open video/}).click();
 await expect(page.locator("video")).toHaveAttribute("preload","metadata");
 await expect.poll(()=>page.locator("video").evaluate((v:HTMLVideoElement)=>v.readyState),{timeout:30000}).toBeGreaterThanOrEqual(1);
 await page.locator("video").evaluate((v:HTMLVideoElement)=>v.play());
 await expect.poll(()=>page.locator("video").evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(0);
 await page.locator("video").focus();await page.keyboard.press("ArrowLeft");
 await expect(page.getByRole("dialog").locator("video")).toBeVisible();
 await expect(page.getByRole("dialog").getByText(/of 2$/)).toBeVisible();
 await page.keyboard.press("Escape");
 await page.screenshot({path:".impeccable/qa/phase6-media-detail-"+testInfo.project.name+".png",fullPage:true});
 await page.goto("/memories");
 await expect(page).toHaveURL(/\/memories$/);await expect(page.getByRole("heading",{name:"Memories, close to home."})).toBeVisible();
 await expect(page.locator('img[loading="lazy"]')).toBeVisible();
 await page.screenshot({path:".impeccable/qa/phase6-gallery-"+testInfo.project.name+".png",fullPage:true});
 await page.goto("/memories/"+fixture.memory);
 await page.getByRole("link",{name:/Show more/}).click();
 for(let i=0;i<2;i++){
  await page.getByRole("button",{name:/Open (photo|video)/}).first().click();
  await page.getByText("Caption and file options",{exact:true}).first().click();await page.getByRole("button",{name:"Remove file",exact:true}).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("button",{name:/Open (photo|video)/})).toHaveCount(1-i);
 }
 await expect(page.getByRole("button",{name:/Open (photo|video)/})).toHaveCount(0);
 await page.reload();await expect(page.getByRole("button",{name:/Open (photo|video)/})).toHaveCount(0);
 expect((await page.request.get(href!,{maxRedirects:0})).status()).toBe(404);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
});
