import {test,expect} from "@playwright/test";
import {readFileSync} from "node:fs";
test("preview galleries keep six photos, all files, captions and file-specific comments",async({page},info)=>{
 test.setTimeout(150000);
 await page.emulateMedia({reducedMotion:"reduce"});await page.goto("/sign-in");await page.getByRole("button",{name:"Enter paired preview"}).click();await expect(page).toHaveURL(/\/home$/);await expect(page.getByRole("link",{name:"Open gallery",exact:true})).toBeVisible();
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Karachi",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
 const png=readFileSync("tests/fixtures/phase6-fixture.png");
 for(const kind of ["memory","moment"] as const){
 await page.goto(kind==="memory"?"/memories/new":"/milestones/new");
 await expect(page.getByLabel("Latitude",{exact:true})).toHaveCount(0);
 await page.getByLabel(kind==="memory"?"Memory title":"Moment name",{exact:true}).fill("Gallery "+kind);
 await page.getByLabel("Date",{exact:true}).fill(today);
 await page.getByLabel("Choose photos or videos").setInputFiles(Array.from({length:7},(_,i)=>({name:"photo-"+i+".png",mimeType:"image/png",buffer:png})));
 await page.getByLabel("Caption for file 1",{exact:true}).fill("First "+kind+" photo");
 await page.getByRole("button",{name:kind==="memory"?"Save the memory":"Save the moment",exact:true}).click();
 await expect(page.getByText("7 photos · 0 videos",{exact:true})).toBeVisible({timeout:45000});
 await page.getByRole("link",{name:"View "+kind,exact:true}).click();await expect(page).toHaveURL(new RegExp((kind==="memory"?"/memories/":"/milestones/")+"[0-9a-f-]+$"));
 await expect(page.getByRole("button",{name:/Open photo/})).toHaveCount(6);
 await expect(page.getByRole("heading",{name:"Remind me",exact:true})).toHaveCount(0);
 const entryUrl=page.url();
 await page.goto(kind==="memory"?"/memories":"/milestones");
 const card=page.getByRole("article").filter({has:page.getByRole("heading",{name:"Gallery "+kind,exact:true})});
 await card.scrollIntoViewIfNeeded();await expect(card.getByRole("button",{name:/Open photo/})).toHaveCount(6);
 await card.getByRole("button",{name:"Open photo 1",exact:true}).click();
 const previewDialog=page.getByRole("dialog");
 if(info.project.name.includes("mobile")){
  const swipe=previewDialog.getByLabel("Swipe photo");
  const bounds=await swipe.boundingBox();expect(bounds).not.toBeNull();
  const cdp=await page.context().newCDPSession(page),x=bounds!.x+bounds!.width*0.8,y=bounds!.y+bounds!.height/2;
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x,y}]});
  await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:x-120,y}]});
  await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await cdp.detach();
 }else await page.keyboard.press("ArrowRight");
 await expect(previewDialog.getByText("2 of 7",{exact:true})).toBeVisible();
 await page.keyboard.press("Escape");
 await page.screenshot({path:".impeccable/qa/gallery-list-"+kind+"-"+info.project.name+".png",fullPage:true});
 await card.getByRole("link",{name:/Show more/}).click();await expect(page).toHaveURL(/gallery\?kind=/);
 await expect(page.getByRole("button",{name:/Open photo/})).toHaveCount(7);
 await expect(page.getByLabel("From",{exact:true})).toBeDisabled();
 await page.getByRole("button",{name:"Open photo 1",exact:true}).click();
 const dialog=page.getByRole("dialog",{name:"Media viewer"});
 await expect(dialog).toBeVisible();await expect.poll(()=>dialog.locator("img").evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true);
 await dialog.getByLabel("Comment on this file").fill("Just for the first "+kind+" photo");await dialog.getByRole("button",{name:"Post comment",exact:true}).click();
 await expect(dialog.getByText("Just for the first "+kind+" photo",{exact:true})).toBeVisible();
 await dialog.getByText("Caption and file options",{exact:true}).click();await dialog.getByLabel("Caption",{exact:true}).fill("Edited "+kind+" caption");await dialog.getByRole("button",{name:"Save caption",exact:true}).click();
 await expect(dialog.getByText("Edited "+kind+" caption",{exact:true})).toBeVisible();
 await dialog.getByRole("button",{name:"Next",exact:true}).click();await expect(dialog.getByText("2 of 7",{exact:true})).toBeVisible();await expect(dialog.getByText("Just for the first "+kind+" photo",{exact:true})).toHaveCount(0);
 await dialog.getByRole("button",{name:"Previous",exact:true}).click();await expect(dialog.getByText("Just for the first "+kind+" photo",{exact:true})).toBeVisible();
 if(kind==="memory")await page.screenshot({path:".impeccable/qa/gallery-viewer-"+info.project.name+".png"});
 await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await page.reload();
 await page.getByRole("button",{name:"Open photo 1",exact:true}).click();await expect(dialog.getByText("Edited "+kind+" caption",{exact:true})).toBeVisible();await expect(dialog.getByText("Just for the first "+kind+" photo",{exact:true})).toBeVisible();await page.keyboard.press("Escape");
 await page.screenshot({path:".impeccable/qa/gallery-preview-"+kind+"-"+info.project.name+".png",fullPage:true});
 await page.goto(entryUrl);
 }
 await page.getByLabel("Choose photos or videos").setInputFiles("tests/fixtures/phase6-video.mp4");await page.getByRole("button",{name:"Upload selected files",exact:true}).click();
 await expect(page.getByText("7 photos · 1 videos",{exact:true})).toBeVisible({timeout:30000});await page.getByRole("link",{name:/Show more/}).click();await expect(page).toHaveURL(/gallery\?kind=moment/);await page.getByRole("button",{name:/Open video/}).click();await expect(page.getByRole("dialog").locator("video")).toHaveAttribute("preload","metadata");await page.keyboard.press("Escape");
 await page.goto("/calendar");await expect(page.getByRole("link",{name:/Memory Gallery memory/})).toBeVisible();await expect(page.getByRole("link",{name:/Moment Gallery moment/})).toBeVisible();
 await page.goto("/home");await page.getByRole("link",{name:"Open gallery",exact:true}).click();await expect(page.getByRole("heading",{name:"Your shared gallery.",exact:true})).toBeVisible();
 await expect(page.getByRole("button",{name:/Open (photo|video)/})).toHaveCount(15);
 await page.getByLabel("From",{exact:true}).selectOption("memory");await expect(page.getByRole("button",{name:/Open photo/})).toHaveCount(7);await page.getByRole("button",{name:/Open photo/}).filter({has:page.getByAltText("Edited memory caption",{exact:true})}).click();
 await expect(page.getByRole("dialog").getByText("Just for the first memory photo",{exact:true})).toBeVisible();
 await page.getByRole("dialog").getByLabel("Comment on this file").fill("Added from Home gallery");await page.getByRole("dialog").getByRole("button",{name:"Post comment",exact:true}).click();await expect(page.getByText("Added from Home gallery",{exact:true})).toBeVisible();await page.keyboard.press("Escape");
 await page.getByLabel("From",{exact:true}).selectOption("all");await page.getByLabel("Group by",{exact:true}).selectOption("date");await page.getByLabel("On date",{exact:true}).fill(today);await expect(page.getByRole("button",{name:/Open (photo|video)/})).toHaveCount(15);
 await page.screenshot({path:".impeccable/qa/gallery-date-"+info.project.name+".png",fullPage:true});
 await page.getByLabel("Show",{exact:true}).selectOption("video");await expect(page.getByRole("button",{name:/Open video/})).toHaveCount(1);await expect(page.getByRole("button",{name:/Open photo/})).toHaveCount(0);
 await page.getByRole("button",{name:/Open video/}).click();await expect(page.getByRole("dialog").locator("video")).toBeVisible();await page.keyboard.press("Escape");
 await page.getByLabel("Show",{exact:true}).selectOption("all");await page.getByLabel("Group by",{exact:true}).selectOption("memory");await expect(page.getByRole("button",{name:/Open (photo|video)/})).toHaveCount(15);
 await page.screenshot({path:".impeccable/qa/gallery-home-"+info.project.name+".png",fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
 await page.getByRole("link",{name:"Open memory",exact:true}).click();await expect(page).toHaveURL(new RegExp("/memories/[0-9a-f-]+$"));await page.getByRole("button",{name:"Open photo 1",exact:true}).click();const finalViewer=page.getByRole("dialog");
 for(let i=0;i<7&&!(await finalViewer.getByText("Edited memory caption",{exact:true}).isVisible());i++)await finalViewer.getByRole("button",{name:"Next",exact:true}).click();
 await expect(finalViewer.getByText("Added from Home gallery",{exact:true})).toBeVisible();
});
