"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { ChevronLeft,ChevronRight,CalendarDays } from "lucide-react";
import { Button } from "@/components/ui/button";
import { filterPlans } from "@/app/actions/plans";
import { addDays,calendarDays,plansOnDay,localDate } from "@/lib/plans/calendar";
import type { loadPlans } from "@/lib/plans/data";
type Page = Awaited<ReturnType<typeof loadPlans>>;
type View="upcoming"|"month"|"week";
type Status="planned"|"completed"|"cancelled"|"all";
export function CalendarWorkspace({initial}:{initial:Page}){
 const [page,setPage]=useState(initial),[view,setView]=useState<View>("upcoming"),[status,setStatus]=useState<Status>("planned"),[anchor,setAnchor]=useState(initial.anchor),[selected,setSelected]=useState(initial.anchor),[error,setError]=useState(""),[pending,start]=useTransition();
 function load(v:View,s:Status,d:string,more=false){setError("");start(async()=>{try{const result=await filterPlans({view:v,status:s,date:d,...(more&&page.next?{cursor:page.next}:{})});if(!result.page){setError(result.error!);return;}setPage({...result.page,plans:more?[...page.plans,...result.page.plans]:result.page.plans});setView(v);setStatus(s);setAnchor(d);setSelected(d);}catch{setError("Connection interrupted. Try again.");}});}
 function move(direction:number){const d=new Date(anchor+"T12:00:00Z");if(view==="month"){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+direction);load(view,status,d.toISOString().slice(0,10));}else load(view,status,addDays(anchor,direction*7));}
 const days=view==="upcoming"?[]:calendarDays(view,anchor);
 const dayPlans=plansOnDay(page.plans,selected,page.timezone);
 const time=new Intl.DateTimeFormat("en",{timeZone:page.timezone,month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});
 const dayLabel=(d:string)=>new Intl.DateTimeFormat("en",{timeZone:"UTC",weekday:"short",month:"short",day:"numeric"}).format(new Date(d+"T12:00:00Z"));
 function entries(plans:Page["plans"]){return plans.length?<div className="divide-y">{plans.map(p=><article key={p.id} id={p.id} className="py-5"><p className="text-sm text-muted-foreground">{time.format(new Date(p.starts_at))}{p.ends_at?" – "+time.format(new Date(p.ends_at)):""} · {p.type.replace("_"," ")} · {p.status}</p><h3 className="mt-2 break-words font-display text-2xl"><Link className="inline-flex min-h-11 items-center text-primary hover:underline" href={"/plans/"+p.id}>{p.title}</Link></h3>{p.location?<p className="mt-1 break-words text-sm text-muted-foreground">{p.location}</p>:null}{p.status==="completed"?<Link className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-primary hover:underline" href={"/plans/"+p.id}>Open experience</Link>:null}</article>)}</div>:<div className="py-10"><CalendarDays className="size-7 text-primary" aria-hidden="true"/><h3 className="mt-4 font-display text-2xl">A little room for something good.</h3><p className="mt-2 text-muted-foreground">No {status==="all"?"":status+" "}plans in this view.</p><Button asChild variant="outline" className="mt-5"><Link href="/plans/new">Plan something</Link></Button></div>;}
 return <section className="mt-8" aria-label="Shared calendar" aria-busy={pending}>
   <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-1 rounded-lg bg-secondary p-1" aria-label="Calendar view">{(["upcoming","month","week"] as const).map(v=><Button key={v} variant={view===v?"default":"ghost"} aria-pressed={view===v} disabled={pending} onClick={()=>load(v,status,selected)}>{v[0].toUpperCase()+v.slice(1)}</Button>)}</div><label className="flex min-h-11 items-center gap-3 text-sm font-semibold">Show<select value={status} disabled={pending} onChange={e=>load(view,e.target.value as Status,anchor)} className="min-h-11 rounded-lg border bg-field px-3">{(["planned","completed","cancelled","all"] as const).map(s=><option key={s} value={s}>{s==="all"?"All plans":s[0].toUpperCase()+s.slice(1)}</option>)}</select></label></div>
   <p className="mt-4 text-sm text-muted-foreground">Times shown in {page.timezone}.</p>
   {error?<p className="status-message status-error mt-4" role="alert">{error}</p>:null}
   {view==="upcoming"?<div className="mt-6"><h2 className="font-display text-3xl">{status==="planned"?"Coming up":status==="completed"?"Completed experiences":status==="cancelled"?"Cancelled plans":"All experiences"}</h2>{entries(page.plans)}</div>:<>
   <div className="my-6 flex flex-wrap items-center justify-between gap-3"><h2 className="font-display text-3xl">{new Intl.DateTimeFormat("en",{timeZone:"UTC",month:"long",year:"numeric"}).format(new Date(anchor+"T12:00:00Z"))}</h2><div className="flex gap-2"><Button variant="outline" disabled={pending} aria-label={"Previous "+view} onClick={()=>move(-1)}><ChevronLeft className="size-4"/></Button><Button variant="outline" disabled={pending} onClick={()=>load(view,status,localDate(new Date(),page.timezone))}>Today</Button><Button variant="outline" disabled={pending} aria-label={"Next "+view} onClick={()=>move(1)}><ChevronRight className="size-4"/></Button></div></div>
   <div className="grid grid-cols-7 border-b">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><div key={d} className="py-2 text-center text-xs font-semibold text-muted-foreground">{d}</div>)}</div>
   <div className="grid grid-cols-7 border-l border-t">{days.map(day=>{const plans=plansOnDay(page.plans,day,page.timezone);return <button type="button" key={day} aria-pressed={selected===day} aria-label={dayLabel(day)+", "+plans.length+" plans"} onClick={()=>setSelected(day)} className={"min-h-16 min-w-0 border-b border-r p-1 text-left transition-colors hover:bg-secondary focus-visible:z-10 focus-visible:outline-2 focus-visible:outline-primary sm:min-h-28 sm:p-3 "+(day===selected?"bg-secondary":"bg-card")}><span className={"block text-center text-sm sm:text-left "+(day.slice(0,7)!==anchor.slice(0,7)?"text-muted-foreground":"font-semibold")}>{Number(day.slice(8))}</span>{plans.length?<><span className="mt-1 block text-center text-xs font-semibold text-primary sm:hidden">{plans.length} <span className="sr-only">plans</span></span><span className="mt-2 hidden space-y-1 sm:block">{plans.slice(0,2).map(p=><span key={p.id} className="block truncate text-xs text-primary">{p.type.replace("_"," ")} · {p.title}</span>)}{plans.length>2?<span className="block text-xs text-muted-foreground">+{plans.length-2} more</span>:null}</span></>:null}</button>;})}</div>
   <div className="mt-8" aria-live="polite"><h2 className="font-display text-3xl">{dayLabel(selected)}</h2>{entries(dayPlans)}</div></>}
   {page.hasMore?<div className="mt-5 border-t pt-5"><p className="mb-3 text-sm text-muted-foreground">More plans are available in this view.</p><Button variant="outline" disabled={pending} onClick={()=>load(view,status,anchor,true)}>{pending?"Loading…":"Load more plans"}</Button></div>:null}
 </section>;
}
