"use client";
import Link from "next/link";
import {SavedLocation} from "@/components/entries/location-field";
import { useActionState,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { ArrowUp,ArrowDown,Trash2 } from "lucide-react";
import { mutatePlan,deletePlanAttachment,uploadPlanAttachment } from "@/app/actions/plans";
import type { PlanDetail } from "@/lib/plans/types";
import { initialActionState } from "@/lib/auth/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SubmitButton } from "@/components/auth/submit-button";
export function PlanDetailView({detail,timezone,preview}:{detail:PlanDetail;timezone:string;preview:boolean}){
 const {plan:p,checklist,reminders,attachments,memoryId}=detail;
 const router=useRouter(),[pending,start]=useTransition(),[message,setMessage]=useState(""),[newStep,setNewStep]=useState(""),[confirm,setConfirm]=useState("");
 const [uploadState,uploadAction]=useActionState(uploadPlanAttachment,initialActionState);
 async function change(input:Record<string,unknown>){setMessage("");start(async()=>{try{const r=await mutatePlan({planId:p.id,version:p.version,...input});if(!r.ok){setMessage(r.message);return;}if(input.operation==="delete"){router.push("/plans");return;}setNewStep("");router.refresh();}catch{setMessage("Connection interrupted. Your changes were not confirmed. Try again.");}});}
 function reorder(index:number,delta:number){const ids=checklist.map(t=>t.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];void change({operation:"checklist",kind:"reorder",ids});}
 const time=new Intl.DateTimeFormat("en",{timeZone:timezone,dateStyle:"medium",timeStyle:"short"});
 return <div className="mx-auto max-w-4xl reveal-on-load"><Link href="/plans" className="inline-flex min-h-11 items-center font-semibold text-primary hover:underline">Back to plans</Link>
 <header className="mt-5 border-b pb-7"><p className="text-sm font-semibold text-primary">{p.type.replace("_"," ")} · {p.status}</p><h1 className="mt-2 break-words font-display text-5xl tracking-[-0.03em]">{p.title}</h1><p className="mt-4 text-lg">{time.format(new Date(p.starts_at))}{p.ends_at?" – "+time.format(new Date(p.ends_at)):""}</p><p className="mt-1 text-sm text-muted-foreground">Shown in {timezone}{p.originating_timezone!==timezone?" · Planned in "+p.originating_timezone:""}</p>{p.location?<p className="mt-4 break-words font-semibold"><SavedLocation value={p.location}/></p>:null}{p.external_map_url?<a href={p.external_map_url} target="_blank" rel="noreferrer" className="mt-2 inline-flex min-h-11 items-center font-semibold text-primary hover:underline">Open map</a>:null}{p.description?<p className="mt-4 max-w-[65ch] whitespace-pre-wrap break-words leading-7 text-muted-foreground">{p.description}</p>:null}{p.budget_minor!=null?<p className="mt-4">Budget: {p.currency} {(p.budget_minor/100).toLocaleString("en",{minimumFractionDigits:2,maximumFractionDigits:2})}</p>:null}
 <div className="mt-5 flex flex-wrap gap-3"><Button asChild variant="outline"><Link href={"/plans/"+p.id+"/edit"}>Edit plan</Link></Button>{p.status==="planned"?<Button disabled={pending} onClick={()=>change({operation:"status",status:"completed"})}>Mark complete</Button>:null}{p.status==="cancelled"?<Button disabled={pending} onClick={()=>change({operation:"status",status:"planned"})}>Restore plan</Button>:null}{p.source_bucket_item_id?<Link href={"/bucket/"+p.source_bucket_item_id} className="inline-flex min-h-11 items-center font-semibold text-primary hover:underline">From your bucket list</Link>:null}</div></header>
 {message?<p role="alert" className="status-message status-error my-5">{message}</p>:null}
 {p.status==="completed"?<section className="my-8 rounded-panel bg-secondary p-6"><h2 className="font-display text-3xl">Keep a little of this moment.</h2><p className="mt-2 leading-7 text-muted-foreground">The experience stays connected when you save it as a memory.</p><Button asChild className="mt-4"><Link href={memoryId?"/memories/"+memoryId:"/memories/new?plan="+p.id}>{memoryId?"Open saved memory":"Save this memory"}</Link></Button></section>:null}
 <section className="mt-9" aria-labelledby="checklist-title"><div className="flex items-baseline justify-between gap-3"><h2 id="checklist-title" className="font-display text-3xl">The little details</h2><span className="text-sm text-muted-foreground">{checklist.filter(t=>t.is_completed).length} of {checklist.length} done</span></div><p className="mt-2 text-muted-foreground">A short checklist to help you arrive relaxed.</p>
 <div className="mt-5 divide-y">{checklist.map((task,i)=><form key={task.id+task.label} className="py-4" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void change({operation:"checklist",kind:"update",id:task.id,label:form.get("label")});}}><div className="flex items-center gap-3"><label className="grid size-11 shrink-0 place-items-center"><input type="checkbox" checked={task.is_completed} disabled={pending} aria-label={"Complete "+task.label} onChange={e=>change({operation:"checklist",kind:"update",id:task.id,completed:e.target.checked})} className="size-5 accent-primary"/></label><Input name="label" aria-label={"Step "+(i+1)} defaultValue={task.label} maxLength={240} required/><Button variant="outline" disabled={pending}>Save</Button></div><div className="mt-2 flex justify-end gap-2"><Button type="button" variant="ghost" disabled={pending||i===0} aria-label={"Move "+task.label+" up"} onClick={()=>reorder(i,-1)}><ArrowUp className="size-4"/></Button><Button type="button" variant="ghost" disabled={pending||i===checklist.length-1} aria-label={"Move "+task.label+" down"} onClick={()=>reorder(i,1)}><ArrowDown className="size-4"/></Button><Button type="button" variant="ghost" disabled={pending} aria-label={"Remove "+task.label} onClick={()=>change({operation:"checklist",kind:"delete",id:task.id})}><Trash2 className="size-4"/></Button></div></form>)}</div>
 <form className="mt-4" onSubmit={e=>{e.preventDefault();void change({operation:"checklist",kind:"add",label:newStep});}}><Label htmlFor="new-step">Next little step</Label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><Input id="new-step" value={newStep} onChange={e=>setNewStep(e.target.value)} maxLength={240} required placeholder="Book a table, pack a picnic…"/><Button className="shrink-0 whitespace-nowrap" disabled={pending||checklist.length>=50}>Add step</Button></div></form></section>
 <section className="mt-10 border-t pt-8" aria-labelledby="reminders-title"><h2 id="reminders-title" className="font-display text-3xl">A gentle reminder</h2><p className="mt-2 max-w-[65ch] leading-7 text-muted-foreground">{preview?"Reminder editing is available in this preview. Delivery runs only for connected accounts.":"Reminders appear in each partner’s inbox if their plan notifications are on. Delivery is checked every minute."}</p><ul className="mt-4 divide-y">{reminders.map(r=><li key={r.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p>{r.offset_minutes===0?"At the start":r.offset_minutes+" minutes before"}</p><p className="mt-1 text-sm text-muted-foreground">{time.format(new Date(r.due_at))} · {r.state}</p></div>{["pending","cancelled"].includes(r.state)?<Button variant="ghost" disabled={pending} onClick={()=>change({operation:"reminder",kind:"delete",id:r.id})}>Remove reminder</Button>:null}</li>)}</ul>
 {p.status==="planned"?<form className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end" onSubmit={e=>{e.preventDefault();void change({operation:"reminder",kind:"add",minutes:Number(new FormData(e.currentTarget).get("minutes"))});}}><div className="flex-1"><Label htmlFor="reminder-time">Remind us</Label><select id="reminder-time" name="minutes" defaultValue="60" className="mt-2 min-h-12 w-full rounded-lg border bg-field px-4"><option value="0">At the start</option><option value="15">15 minutes before</option><option value="60">1 hour before</option><option value="1440">1 day before</option><option value="10080">1 week before</option></select></div><Button disabled={pending||reminders.length>=5}>Add reminder</Button></form>:null}</section>
 <section className="mt-10 border-t pt-8" aria-labelledby="attachments-title"><h2 id="attachments-title" className="font-display text-3xl">Keep it handy</h2><p className="mt-2 leading-7 text-muted-foreground">Tickets, a reservation, or a map. Private PDF, PNG, or JPEG files, up to 2 MB each.</p>{preview?<p className="mt-4 rounded-control bg-secondary p-4 text-sm">Sign in with your connected account to add and download attachments.</p>:<><ul className="mt-4 divide-y">{attachments.map(a=><li key={a.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="min-w-0">{a.ready?<a className="inline-flex min-h-11 items-center break-all font-semibold text-primary hover:underline" href={"/api/plan-attachments/"+a.id}>{a.filename}</a>:<p className="break-all">{a.filename} · Unfinished upload</p>}<p className="text-sm text-muted-foreground">{Math.ceil(a.size_bytes/1024)} KB</p></div><Button variant="ghost" disabled={pending} onClick={()=>{start(async()=>{try{const r=await deletePlanAttachment({id:a.id,planId:p.id});if(!r.ok)setMessage(r.message);else router.refresh();}catch{setMessage("Connection interrupted. Try removing the attachment again.");}});}}>Remove attachment</Button></li>)}</ul><form action={uploadAction} className="mt-5 space-y-3"><input type="hidden" name="planId" value={p.id}/><Label htmlFor="attachment">Choose a file</Label><Input id="attachment" name="file" type="file" accept="application/pdf,image/png,image/jpeg" required/><SubmitButton>Add attachment</SubmitButton>{uploadState.message?<p role="status" className={uploadState.status==="error"?"field-error":"text-success"}>{uploadState.message}</p>:null}</form></>}</section>
 <section className="mt-12 border-t pt-8"><h2 className="font-display text-2xl">When plans change</h2>{p.status==="planned"?<div className="mt-3"><p className="mb-3 text-sm text-muted-foreground">Cancelling keeps the details and stops pending reminders.</p><Button variant="outline" disabled={pending} onClick={()=>change({operation:"status",status:"cancelled"})}>Cancel plan</Button></div>:null}<details className="mt-5"><summary className="min-h-11 cursor-pointer py-3 font-semibold text-danger">Delete this plan</summary><p className="my-3 max-w-[65ch] text-sm leading-6 text-muted-foreground">Remove attachments first. Deletion removes the checklist and reminders. Saved memories remain.</p><form onSubmit={e=>{e.preventDefault();void change({operation:"delete",confirmation:confirm});}}><Label htmlFor="delete-confirm">Type DELETE to confirm</Label><Input id="delete-confirm" className="my-3 max-w-xs" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/><Button variant="outline" disabled={pending||confirm!=="DELETE"||attachments.length>0}>Delete plan permanently</Button></form></details></section></div>;
}
