"use server";
import {z} from "zod";
import {planContext} from "@/lib/plans/data";
import type {EntryComment,EntryMedia} from "@/lib/entries/types";
const target=z.object({kind:z.enum(["memory","moment"]),id:z.uuid()});
async function context(input:unknown){const a=target.parse(input),c=await planContext();if(!c.paired)throw Error("Open your shared space first.");if(c.kind==="preview"){if(!(a.kind==="memory"?c.state.memories:c.state.milestones).some(x=>x.id===a.id))throw Error("Entry unavailable.");}else{const {data}=await c.db.from(a.kind==="memory"?"memories":"milestones").select("id").eq("id",a.id).maybeSingle();if(!data)throw Error("Entry unavailable.");}return {a,c};}
export async function entryMedia(input:unknown):Promise<{media?:EntryMedia[];error?:string}>{try{const {a,c}=await context(input);if(c.kind==="preview")return {media:[]};const columns="id,caption,media_type,mime_type,state,size_bytes,duration_seconds" as const;const {data,error}=await (a.kind==="memory"?c.db.from("memory_media").select(columns).eq("memory_id",a.id):c.db.from("milestone_media").select(columns).eq("milestone_id",a.id)).order("created_at").limit(30);if(error)throw error;return {media:data};}catch{return {error:"Could not load photos. Check your connection and try again."};}}
export async function entryComments(input:unknown):Promise<{comments?:EntryComment[];error?:string}>{try{const {a,c}=await context(input);if(c.kind==="preview")return {comments:[]};const {data,error}=await c.db.from("entry_comments").select("id,body,created_at,created_by").eq(a.kind==="memory"?"memory_id":"milestone_id",a.id).order("created_at").limit(500);if(error)throw error;return {comments:data.map(x=>({id:x.id,body:x.body,created_at:x.created_at,mine:x.created_by===c.userId}))};}catch{return {error:"Could not load comments."};}}
export async function commentAction(input:unknown){try{const v=target.extend({operation:z.enum(["add","remove"]),body:z.string().trim().min(1).max(2000).optional(),commentId:z.uuid().optional()}).parse(input),{a,c}=await context(v);if(c.kind==="preview")throw Error("Use the local preview comment store.");if(v.operation==="add"){if(!v.body)throw Error("Write a comment first.");const {error}=await c.db.from("entry_comments").insert({memory_id:a.kind==="memory"?a.id:null,milestone_id:a.kind==="moment"?a.id:null,created_by:c.userId,body:v.body});if(error)throw Error("Could not save the comment.");}else{if(!v.commentId)throw Error("Comment unavailable.");const {data,error}=await c.db.from("entry_comments").delete().eq("id",v.commentId).eq("created_by",c.userId).eq(a.kind==="memory"?"memory_id":"milestone_id",a.id).select("id").maybeSingle();if(error||!data)throw Error("Could not remove the comment.");}return {ok:true};}catch(e){return {error:e instanceof Error?e.message:"Could not update comments."};}}
