"use client";
import Link from "next/link";
import { useActionState } from "react";
import { createPlanAction, createMemoryAction } from "@/app/actions/dream";
import { initialActionState } from "@/lib/auth/types";
import type { BucketItem } from "@/lib/bucket/schema";
import { planTypes } from "@/lib/dream/schema";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { bucketFieldClass } from "./bucket-workspace";

export function BucketConversionForm({ item, mode, timezone = "UTC" }: { item: BucketItem; mode: "plan" | "memory"; timezone?: string }) {
  const [state, action, pending] = useActionState(mode === "plan" ? createPlanAction : createMemoryAction, initialActionState);
  return <div className="mx-auto max-w-2xl"><Link className="inline-flex min-h-11 items-center font-semibold text-primary" href={`/bucket/${item.id}`}>Back to the idea</Link><p className="mt-5 text-sm font-semibold text-primary">{mode === "plan" ? "From a bucket idea" : "From a completed bucket idea"}</p><h1 className="mt-2 font-display text-4xl">{mode === "plan" ? "Give someday a date." : "Keep what mattered."}</h1><p className="mt-4 leading-7 text-muted-foreground">Review the details below. The link to your idea stays with {mode === "plan" ? "the plan" : "this memory"}.</p><form action={action} className="mt-8 space-y-5"><input type="hidden" name="sourceBucketId" value={item.id} /><label className="block space-y-2 font-semibold">{mode === "plan" ? "What are you planning?" : "Memory title"}<Input name="title" defaultValue={item.title} required maxLength={160} /></label><label className="block space-y-2 text-sm font-semibold">{mode === "plan" ? "A few details" : "What do you want to remember?"}<textarea name="description" className={bucketFieldClass} rows={4} defaultValue={item.description ?? ""} maxLength={mode === "plan" ? 8000 : 12000} /></label><label className="block space-y-2 text-sm font-semibold">Location<Input name="location" defaultValue={item.location ?? ""} maxLength={240} /></label>
      {mode === "plan" ? <><label className="block space-y-2 text-sm font-semibold">Kind of plan<select aria-label="Kind of plan" name="type" className={bucketFieldClass}>{planTypes.map((type) => <option key={type}>{type}</option>)}</select></label><div className="grid gap-5 sm:grid-cols-2"><label className="space-y-2 text-sm font-semibold">Starts<Input name="startsAt" type="datetime-local" required defaultValue={item.target_date ? `${item.target_date}T12:00` : ""} /></label><label className="space-y-2 text-sm font-semibold">Ends <span className="font-normal">optional</span><Input name="endsAt" type="datetime-local" /></label></div><label className="block space-y-2 text-sm font-semibold">Timezone<Input name="timezone" defaultValue={timezone} required /></label><div className="grid grid-cols-[minmax(0,1fr)_7rem] gap-3"><label className="space-y-2 text-sm font-semibold">Budget<Input name="budget" inputMode="decimal" defaultValue={item.estimated_cost_minor == null ? "" : (item.estimated_cost_minor / 100).toFixed(2)} /></label><label className="space-y-2 text-sm font-semibold">Currency<Input name="currency" defaultValue={item.currency ?? ""} maxLength={3} /></label></div></> : <><input name="sourcePlanId" type="hidden" value="" /><label className="block space-y-2 text-sm font-semibold">Date<Input name="memoryDate" type="date" defaultValue={item.completed_at?.slice(0, 10)} required /></label><label className="block space-y-2 text-sm font-semibold">How it felt<select aria-label="How it felt" name="rating" className={bucketFieldClass}><option value="">No rating</option>{[5,4,3,2,1].map((n) => <option key={n} value={n}>{n} / 5</option>)}</select></label><label className="flex min-h-11 items-center gap-3 text-sm"><input name="favorite" type="checkbox" className="size-5 accent-primary" />Keep as a favorite</label></>}
      <p role="status" className="min-h-6 text-sm text-danger">{state.message}</p>{state.fields ? <ul className="text-sm text-danger">{Object.entries(state.fields).map(([key, errors]) => <li key={key}>{key}: {errors[0]}</li>)}</ul> : null}<div className="flex flex-wrap gap-3"><Button disabled={pending}>{pending ? "Saving…" : mode === "plan" ? "Save this plan" : "Save the memory"}</Button><Button asChild variant="ghost"><Link href={`/bucket/${item.id}`}>Cancel</Link></Button></div></form></div>;
}
