"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { ArrowDown, ArrowUp, Check } from "lucide-react";
import { mutateBucket } from "@/app/actions/bucket";
import { moveSubtask, subtaskProgress, type BucketItem, type BucketSubtask } from "@/lib/bucket/schema";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function ItemDetail({ item, subtasks }: { item: BucketItem; subtasks: BucketSubtask[] }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [message, setMessage] = useState("");
  const progress = subtaskProgress(subtasks);
  function submit(command: unknown, success: string, after?: () => void) {
    start(async () => { try { const result = await mutateBucket(command); setMessage(result.ok ? success : result.message); if (result.ok) { router.refresh(); after?.(); } } catch { setMessage("Connection interrupted. Try again when you are online."); } });
  }
  function step(kind: "add" | "update" | "delete" | "reorder", task: BucketSubtask | null, label = "", completed = false, orderedIds: string[] = []) {
    submit({ operation: "subtask", id: item.id, version: item.version, kind, subtaskId: task?.id ?? null, label, completed, orderedIds }, kind === "reorder" ? "Step order saved." : "Steps updated.");
  }
  return <div>
    <div className="mt-6 flex flex-wrap gap-3">{item.status === "completed" ? <section className="w-full rounded-2xl bg-secondary p-6"><h2 className="font-display text-3xl">One more dream lived.</h2><p className="mt-2 leading-7 text-muted-foreground">Completion is saved. Your story can follow when you are ready.</p><Button asChild className="mt-5"><Link href={`/memories/new?bucket=${item.id}`}>Save this as a memory</Link></Button></section> : <><Button asChild><Link href={`/plans/new?bucket=${item.id}`}>Plan this</Link></Button><Button variant="outline" disabled={pending} onClick={() => submit({ operation: "completeItem", id: item.id, version: item.version }, "One more dream lived. Completion saved.")}><Check className="size-4" />Mark complete</Button></>}</div>
    <p role="status" className="mt-5 min-h-6 text-sm text-primary">{pending ? "Saving…" : message}</p>
    <section className="mt-7 border-t pt-7" aria-labelledby="steps-title"><div className="flex flex-wrap items-baseline justify-between gap-3"><h2 id="steps-title" className="font-display text-3xl">Little steps</h2><p className="text-sm text-muted-foreground">{progress.completed} of {progress.total} complete</p></div><progress className="mt-4 h-2 w-full overflow-hidden rounded-full bg-secondary [&::-webkit-progress-bar]:bg-secondary [&::-webkit-progress-value]:bg-primary [&::-moz-progress-bar]:bg-primary" aria-label="Subtask progress" value={progress.completed} max={Math.max(1, progress.total)} />
      <p className="mt-3 text-sm leading-6 text-muted-foreground">Use the up and down buttons to change the order. Each idea can hold 50 steps.</p>
      <ol className="mt-5 divide-y">{subtasks.map((task, index) => <li key={task.id} className="py-4"><form onSubmit={(event) => { event.preventDefault(); step("update", task, String(new FormData(event.currentTarget).get("label")), task.is_completed); }}><div className="flex items-center gap-3"><label className="grid min-h-11 min-w-11 shrink-0 cursor-pointer place-items-center"><input type="checkbox" className="size-5 accent-primary" aria-label={`Complete ${task.label}`} checked={task.is_completed} disabled={pending} onChange={(event) => step("update", task, task.label, event.target.checked)} /></label><Input name="label" aria-label={`Step ${index + 1}`} defaultValue={task.label} key={task.label} required maxLength={240} className={task.is_completed ? "line-through text-muted-foreground" : ""} /></div><div className="mt-3 flex flex-wrap gap-2"><Button variant="ghost" size="sm" disabled={pending}>Save step</Button><Button variant="ghost" size="sm" type="button" disabled={pending || index === 0} aria-label={`Move ${task.label} up`} onClick={() => step("reorder", null, "", false, moveSubtask(subtasks.map((task) => task.id), task.id, -1))}><ArrowUp className="size-4" />Up</Button><Button variant="ghost" size="sm" type="button" disabled={pending || index === subtasks.length - 1} aria-label={`Move ${task.label} down`} onClick={() => step("reorder", null, "", false, moveSubtask(subtasks.map((task) => task.id), task.id, 1))}><ArrowDown className="size-4" />Down</Button><Button variant="ghost" size="sm" type="button" disabled={pending} onClick={() => step("delete", task)}>Remove step</Button></div></form></li>)}</ol>
      <form className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const label = String(new FormData(form).get("label")); submit({ operation: "subtask", id: item.id, version: item.version, kind: "add", subtaskId: null, label, completed: false, orderedIds: [] }, "Step added.", () => form.reset()); }}><label className="flex-1 space-y-2 text-sm font-semibold">Next little step<Input name="label" required maxLength={240} placeholder="What would bring this closer?" /></label><Button variant="outline" disabled={pending || subtasks.length >= 50}>Add step</Button></form>
    </section>
    <details className="mt-10 border-t pt-5"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Delete this idea</summary><p className="max-w-prose text-sm leading-6 text-muted-foreground">This permanently removes the idea and its steps from both shared lists. Existing plans and memories are kept, but their link to this idea is removed.</p><form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); submit({ operation: "deleteItem", id: item.id, version: item.version, confirmation: new FormData(event.currentTarget).get("confirmation") }, "Idea deleted.", () => router.push("/bucket")); }}><label className="block space-y-2 text-sm">Type DELETE to confirm<Input name="confirmation" required pattern="DELETE" /></label><Button variant="outline" disabled={pending}>Delete idea permanently</Button></form></details>
  </div>;
}
